-- 성분으로 구분한 아이스크림 총 주문량

-- 코드를 입력하세요
SELECT I.INGREDIENT_TYPE, SUM(FH.TOTAL_ORDER) AS TOTAL_ORDER
FROM ICECREAM_INFO I, FIRST_HALF FH
WHERE I.FLAVOR = FH.FLAVOR
GROUP BY I.INGREDIENT_TYPE
ORDER BY FH.TOTAL_ORDER
