--  우유와 요거트가 담긴 장바구니

-- 코드를 입력하세요
SELECT A.CART_ID
FROM 
(SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = 'Yogurt') as A, (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = 'Milk') as B
WHERE A.CART_ID = B.CART_ID
ORDER BY CART_ID
